root_folder: artifacts

data_source_url: "https://github.com/RanganathJoshi/End-End-Projects/raw/master/notebooks/data/gemstone.zip"
raw_data: artifacts/gemstone.zip
unzip: artifacts
train_data: artifacts/train.csv
valid_data: artifacts/valid.csv
test_data: artifacts/test.csv